name: Execute tests on Dev branch

on: 
  push:
    branches:
      - dev

jobs:
  test:
    name: Execute tests
    uses: ./.github/workflows/UnityTests.yml
    secrets: inherit
    
  merge-branch:
    name: Merge to Main branch
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - name: Merge Dev to Main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}